version: '3.2'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: authority_db
    ports:
      - "3311:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/db/authority_db.sql:/docker-entrypoint-initdb.d/authority_db.sql

volumes:
  mysql_data: